venta_index:
    path:     /lista_ventas/{id_cliente}/{mes}/{ano}
    defaults: { _controller: "ContabilidadBundle:VentaSin:index" }
    methods:  [GET, POST]

venta_new:
    path:     /{id_cliente}/{mes}/{ano}/new
    defaults: { _controller: "ContabilidadBundle:VentaSin:new" }
    methods:  [GET, POST]

venta_show:
    path:     /{id_cliente}/{mes}/{ano}/{id_venta}/show
    defaults: { _controller: "ContabilidadBundle:VentaSin:show" }
    methods:  GET

venta_edit:
    path:     /{id_cliente}/{mes}/{ano}/{id_venta}/edit
    defaults: { _controller: "ContabilidadBundle:VentaSin:edit" }
    methods:  [GET, POST]

venta_delete:
    path:     /{id}/delete
    defaults: { _controller: "ContabilidadBundle:VentaSin:delete" }
    methods:  DELETE
