<?php

namespace PersonalBundle\Repository;

/**
 * SueldoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SueldoRepository extends \Doctrine\ORM\EntityRepository
{
}
