imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PersonalBundle/Resources/config/services.yml" }
    - { resource: "@ContabilidadBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            - "bootstrap_3_horizontal_layout.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                convert_tz: AppBundle\Query\Mysql\ConvertTz
                date: AppBundle\Query\Mysql\Date
                date_format: AppBundle\Query\Mysql\DateFormat
                dateadd: AppBundle\Query\Mysql\DateAdd
                datesub: AppBundle\Query\Mysql\DateSub
                datediff: AppBundle\Query\Mysql\DateDiff
                day: AppBundle\Query\Mysql\Day
                dayname: AppBundle\Query\Mysql\DayName
                dayofweek: AppBundle\Query\Mysql\DayOfWeek
                dayofyear: AppBundle\Query\Mysql\DayOfYear
                div: AppBundle\Query\Mysql\Div
                from_unixtime: AppBundle\Query\Mysql\FromUnixtime
                hour: AppBundle\Query\Mysql\Hour
                last_day: AppBundle\Query\Mysql\LastDay
                minute: AppBundle\Query\Mysql\Minute
                now: AppBundle\Query\Mysql\Now
                month: AppBundle\Query\Mysql\Month
                monthname: AppBundle\Query\Mysql\MonthName
                second: AppBundle\Query\Mysql\Second
                strtodate: AppBundle\Query\Mysql\StrToDate
                time: AppBundle\Query\Mysql\Time
                timediff: AppBundle\Query\Mysql\TimeDiff
                timestampadd: AppBundle\Query\Mysql\TimestampAdd
                timestampdiff: AppBundle\Query\Mysql\TimestampDiff
                timetosec: AppBundle\Query\Mysql\TimeToSec
                week: AppBundle\Query\Mysql\Week
                weekday: AppBundle\Query\Mysql\WeekDay
                year: AppBundle\Query\Mysql\Year
                yearweek: AppBundle\Query\Mysql\YearWeek
                unix_timestamp: AppBundle\Query\Mysql\UnixTimestamp


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
