<?php

namespace ContabilidadBundle\Repository;

/**
 * CompracRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\Query\ResultSetMapping;

class CompracRepository extends \Doctrine\ORM\EntityRepository
{

    public function filtrarCompras($opciones=array(
        'cliente'=>0
    ))
    {
        $em=$this->getEntityManager();

        $query=$em->createQueryBuilder()
            ->select('c')
            ->from('Comprac.php', 'c')
            ->Where("c.cliente = :cliente")
            ->setParameter('cliente', $opciones['cliente'])
            ->orderBy('c.fecha', 'ASC')
            ->getQuery();

        $compras=$query->getResult();
        return $compras;
    }

    public function filtrarComprasPeriodo($opciones=array(
        'cliente'=>0,
        'mes',
        'ano'
    ))
    {
        $em=$this->getEntityManager();

        $rsm = new ResultSetMapping();
        // build rsm here

        $query = $em->createQueryBuilder()
            ->select('c')
            ->from('ContabilidadBundle:Comprac', 'c')
            ->Where('c.cliente = :cliente')
            ->andWhere('month(c.fecha) =  :mes')
            ->andWhere('year(c.fecha) = :ano')
            ->setParameter('cliente', $opciones['cliente'])
            ->setParameter('mes', $opciones['mes'])
            ->setParameter('ano', $opciones['ano'])
            ->orderBy('c.fecha', 'ASC')
            ->addOrderBy('c.id', 'ASC')
            ->getQuery();

        $resultado = $query->getResult();

        return $resultado;
    }


    public function totalesCompras($opciones=array(
        'cliente'=>0,
        'mes',
        'ano'
    ))
    {
        $em=$this->getEntityManager()->getRepository('ContabilidadBundle:Comprac');

        $query=$em->createQueryBuilder('c')
            ->Select('COUNT(distinct c.id) AS cantidad, sum(d.g10+d.g5+d.iva10+d.iva5+d.exe) as suma')
            ->leftJoin('c.comprad', 'd', 'ON')
            ->andWhere("c.cliente = :cliente")
            ->andWhere("month(c.fecha) = :mes")
            ->andWhere("year(c.fecha) = :ano")
            ->setParameter('cliente', $opciones['cliente'])
            ->setParameter('mes', $opciones['mes'])
            ->setParameter('ano', $opciones['ano'])
            ->getQuery();

        $compras=$query->getResult();
        return $compras;
    }
}
