<?php

namespace ContabilidadBundle\Repository;

/**
 * CompradRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompradRepository extends \Doctrine\ORM\EntityRepository
{


}
