<?php

namespace ContabilidadBundle\Repository;

/**
 * CuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaRepository extends \Doctrine\ORM\EntityRepository
{
    public function encontrarCuenta($cuenta)
    {
        $em=$this->getEntityManager()->getRepository('ContabilidadBundle:Cuenta');
        $query = $em->createQueryBuilder('c')
            ->where("c.cuenta like :cuenta")
            ->setParameter('cuenta', '%'.$cuenta.'%')
            ->getQuery();

        $resultado=$query->getResult();

        return $resultado;
    }
}
