<?php

namespace ContabilidadBundle\Repository;

/**
 * EntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadRepository extends \Doctrine\ORM\EntityRepository
{
    public function encontrarEntidad($nombre)
    {
        $em=$this->getEntityManager()->getRepository('ContabilidadBundle:Entidad');
        $query = $em->createQueryBuilder('e')
            ->where("e.nombre like :nombre")
            ->setParameter('nombre', '%'.$nombre.'%')
            ->getQuery();

        $resultado=$query->getResult();

        return $resultado;
    }
}
