<?php

namespace ContabilidadBundle\Repository;

/**
 * EntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadRepository extends \Doctrine\ORM\EntityRepository
{
    public function encontrarEntidad($ruc)
    {
        $em=$this->getEntityManager()->getRepository('ContabilidadBundle:Entidad');
        $entidad = $em->findOneByRUC($ruc);

        if($entidad=null){
            $entidad='NO ENCONTRADO';
        }

        return $entidad;
    }
}
