<?php

namespace ContabilidadBundle\Repository;

/**
 * FacturaCabeceraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaCabeceraRepository extends \Doctrine\ORM\EntityRepository
{
}
