<?php

namespace ContabilidadBundle\Repository;

/**
 * PeriodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function filtrarPeriodos($opciones=array(
        'cliente'=>0
    ))
    {
        $em=$this->getEntityManager();

        $query=$em->createQueryBuilder()
            ->select('p')
            ->from('ContabilidadBundle:Periodo', 'p')
            ->Where("p.cliente = :cliente")
            ->setParameter('cliente', $opciones['cliente'])
            ->orderBy('p.ano', 'DESC')
            ->addorderBy('p.mes', 'DESC')
            ->getQuery();

        $ventas=$query->getResult();
        return $ventas;
    }
}
