<?php

namespace ContabilidadBundle\Repository;

/**
 * PlanCtaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanCtaRepository extends \Doctrine\ORM\EntityRepository
{

}
