<?php

namespace ContabilidadBundle\Repository;

/**
 * SucursalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SucursalRepository extends \Doctrine\ORM\EntityRepository
{
}
