<?php

namespace ContabilidadBundle\Repository;

/**
 * VentacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\Query\ResultSetMapping;

class VentacRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIVA10($ii10)
    {
        $iva10=round(($ii10/11),0);
        return $iva10;
    }

    public function filtrarVentas($opciones=array(
        'cliente'=>0
    ))
    {
        $em=$this->getEntityManager();

        $query=$em->createQueryBuilder()
            ->select('v')
            ->from('Ventac.php', 'v')
            ->Where("v.cliente = :cliente")
            ->setParameter('cliente', $opciones['cliente'])
            ->orderBy('v.fecha', 'ASC')
            ->getQuery();

        $ventas=$query->getResult();
        return $ventas;
    }

    public function filtrarVentasPeriodo($opciones=array(
        'cliente'=>0,
        'mes',
        'ano'
    ))
    {
        $em=$this->getEntityManager();

        $rsm = new ResultSetMapping();
        // build rsm here

        $query = $em->createQueryBuilder()
            ->select('v')
            ->from('ContabilidadBundle:Ventac', 'v')
            ->Where('v.cliente = :cliente')
            ->andWhere('month(v.fecha) =  :mes')
            ->andWhere('year(v.fecha) = :ano')
            ->setParameter('cliente', $opciones['cliente'])
            ->setParameter('mes', $opciones['mes'])
            ->setParameter('ano', $opciones['ano'])
            ->orderBy('v.fecha', 'ASC')
            ->getQuery();

        $resultado = $query->getResult();

        return $resultado;
    }


    public function totalesVentas($opciones=array(
        'cliente'=>0,
        'mes',
        'ano'
    ))
    {
        $em=$this->getEntityManager()->getRepository('ContabilidadBundle:Ventac');

        $query=$em->createQueryBuilder('v')
            ->Select('COUNT(1) AS cantidad, sum(d.g10+d.g5+d.iva10+d.iva5+d.exe) as suma')
            ->leftJoin('v.ventad', 'd', 'ON', null, 'd.id')
            ->andWhere("v.cliente = :cliente")
            ->andWhere("month(v.fecha) = :mes")
            ->andWhere("year(v.fecha) = :ano")
            ->setParameter('cliente', $opciones['cliente'])
            ->setParameter('mes', $opciones['mes'])
            ->setParameter('ano', $opciones['ano'])
            ->getQuery();

//            ->select('sum(d.g10+d.g5+d.iva10+d.iva5+d.exe) as suma')
//            ->leftJoin('v.ventad', 'd', 'Join::WITH')
        $ventas=$query->getResult();
//        dump($ventas);
        return $ventas;
    }
}
