<?php

namespace ContabilidadBundle\Repository;

use DoctrineExtensions\Query\Mysql\Month;
use DoctrineExtensions\Query\Mysql\Year;

/**
 * VentaSinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
$classLoader = new \Doctrine\Common\ClassLoader('DoctrineExtensions', 'AppBundle/Query/');
$classLoader->register();


class VentaSinRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIVA10($ii10)
    {
        $iva10=round(($ii10/11),0);
        return $iva10;
    }

    public function filtrarVentas($opciones=array(
        'cliente'=>0
    ))
    {
        $em=$this->getEntityManager();

        $query=$em->createQueryBuilder()
            ->select('v')
            ->from('ContabilidadBundle:VentaSin', 'v')
            ->Where("v.cliente = :cliente")
            ->setParameter('cliente', $opciones['cliente'])
            ->orderBy('v.fecha', 'ASC')
            ->getQuery();

        $ventas=$query->getResult();
        return $ventas;
    }

    public function filtrarVentasPeriodo($opciones=array(
        'cliente'=>0,
        'mes',
        'ano'
    ))
    {
        $em=$this->getEntityManager();

        $query = $em->createQuery('SELECT v FROM ContabilidadBundle:Ventasin v WHERE v.cliente=?1 AND MONTH(v.fecha)=?2 AND YEAR(v.fecha)=?3');
        $query->setParameter(1, $opciones['cliente']);
        $query->setParameter(2, $opciones['mes']);
        $query->setParameter(3, $opciones['ano']);

        $resultado=$query->getResult();
        return $resultado;
    }
}
