<?php

namespace ContabilidadBundle\Repository;

/**
 * VentaDetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaDetRepository extends \Doctrine\ORM\EntityRepository
{
}
