<?php

namespace ContabilidadBundle\Repository;

/**
 * VentaSinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaSinRepository extends \Doctrine\ORM\EntityRepository
{
}
