<?php

namespace ContabilidadBundle\Repository;

/**
 * VentaSinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaSinRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIVA10($ii10)
    {
        $iva10=round(($ii10/11),0);
        return $iva10;
    }
}
