<?php

namespace ContabilidadBundle\Repository;

/**
 * VentadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentadRepository extends \Doctrine\ORM\EntityRepository
{


}
