contabilidad_venta:
    resource: "@ContabilidadBundle/Resources/config/routing/ventasin.yml"
    prefix:   /venta

contabilidad_menu:
    path:     /
    defaults: { _controller: ContabilidadBundle:Default:index }

contabilidad_lista_clientes:
    path:     /lista_clientes
    defaults: { _controller: ContabilidadBundle:Default:filtrarClientes}