contabilidad_menu:
    path:     /
    defaults: { _controller: ContabilidadBundle:Default:index }

contabilidad_venta:
    resource: "@ContabilidadBundle/Resources/config/routing/ventasin.yml"
    prefix:   /venta

contabilidad_cliente:
    resource: "@ContabilidadBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente



